version: "3.9"
   
services:
  pipeline_db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pipeline_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pipeline_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  gov_db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - gov_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gov_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - MINIO_ACCESS_KEY=myaccesskey
  #     - MINIO_SECRET_KEY=mysecretkey
  #   volumes:
  #     - ./data:/data
  #   command: server /data
      
volumes:
  pipeline_db_data:
    driver: local

  gov_db_data:
    driver: local