# Generated by Django 3.2.5 on 2023-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascrap',
            name='img_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
