# Generated by Django 3.2.5 on 2023-09-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datascrap',
            old_name='title',
            new_name='designation',
        ),
    ]
