# Generated by Django 3.2.5 on 2023-10-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datascrap_img_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datascrap',
            name='img_link',
        ),
        migrations.AddField(
            model_name='datascrap',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
