# Generated by Django 3.2.5 on 2023-09-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='dep',
            field=models.CharField(default='Unknown Department', max_length=255),
        ),
        migrations.AddField(
            model_name='leadership',
            name='email',
            field=models.CharField(default='Unknown Email', max_length=255),
        ),
        migrations.AddField(
            model_name='leadership',
            name='phone_number',
            field=models.CharField(default='Unknown Phone Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=255),
        ),
    ]
