# Generated by Django 3.2.5 on 2023-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_title_datascrap_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascrap',
            name='hierarchy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datascrap',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
