# Generated by Django 3.2.5 on 2023-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20230918_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='phone_number',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
