# Generated by Django 3.2.5 on 2023-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20230921_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
