# Generated by Django 3.2.5 on 2023-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20231006_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScrapImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datascrap',
            name='img',
        ),
    ]
