# Generated by Django 3.2.5 on 2023-10-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20231006_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datascrapimages',
            old_name='image_data',
            new_name='img',
        ),
    ]
