# Generated by Django 3.2.5 on 2023-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_leadership_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
