# Generated by Django 3.2.5 on 2023-09-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_csvfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascrap',
            name='validation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
