# Generated by Django 3.2.5 on 2023-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_datascrap_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascrap',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
