# Generated by Django 3.2.5 on 2023-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_leadership_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='dep',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='email',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='title',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
