# Generated by Django 3.2.5 on 2023-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20230918_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='validate',
            field=models.BooleanField(default=True),
        ),
    ]
