# Generated by Django 3.2.5 on 2023-10-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_datascrapimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascrapimages',
            name='data_scrap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.datascrap'),
        ),
    ]
