# Generated by Django 3.2.5 on 2023-10-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_datascrapimages_data_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascrap',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datascrap',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datascrap',
            name='image_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
