# Generated by Django 3.2.5 on 2023-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20230918_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='validate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
