# Generated by Django 3.2.5 on 2023-10-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20231011_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataScrapImages',
        ),
    ]
