# Generated by Django 3.2.5 on 2023-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_leadership_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
