# Generated by Django 3.2.5 on 2023-10-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_delete_datascrapimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascrap',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='dep',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='designation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='email',
            field=models.EmailField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='hierarchy',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datascrap',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
