# Generated by Django 3.2.5 on 2023-10-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20231014_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_data', models.TextField(blank=True, null=True)),
                ('data_scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.datascrap')),
            ],
        ),
    ]
