# Generated by Django 4.1.12 on 2023-11-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascrap',
            name='phone_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
