# Generated by Django 4.1.12 on 2024-01-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='data',
            name='subcommittee',
        ),
        migrations.AddField(
            model_name='data',
            name='committee',
            field=models.ManyToManyField(blank=True, to='legislative.committees'),
        ),
        migrations.AddField(
            model_name='data',
            name='subcommittee',
            field=models.ManyToManyField(blank=True, to='legislative.subcommittees'),
        ),
    ]
