# Generated by Django 4.1.12 on 2024-01-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0004_remove_data_committee_remove_data_subcommittee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeCSVFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
