# Generated by Django 4.1.12 on 2024-01-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0005_legislativecsvfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committees',
            name='hierarchy',
        ),
    ]
