# Generated by Django 4.1.12 on 2024-01-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0010_remove_data_committee_remove_data_hierarchy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislative.committees'),
        ),
        migrations.AlterField(
            model_name='data',
            name='hierarchy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislative.hierarchy'),
        ),
        migrations.AlterField(
            model_name='data',
            name='subcommittee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislative.subcommittees'),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislative.title'),
        ),
    ]
