# Generated by Django 4.1.12 on 2024-02-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0012_members_member_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('party', models.CharField(blank=True, max_length=128, null=True)),
                ('employer', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('member_title', models.CharField(blank=True, max_length=512, null=True)),
                ('committee_title', models.CharField(blank=True, max_length=512, null=True)),
                ('committee', models.CharField(blank=True, max_length=512, null=True)),
                ('subcommittee', models.CharField(blank=True, max_length=512, null=True)),
                ('hierarchy', models.CharField(max_length=512)),
                ('image_name', models.TextField(blank=True, null=True)),
                ('subcommittee_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('committee_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('member_link', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
